### PR TITLE
Added fetchWorkoutCSV feature to export Polar's activities

### PR DESCRIPTION
**Pull request by JavierMartinz**
No more patches, I promise :neckbeard:

### CODE REVIEW

**Comment by dragosprotung** [comment]
Do you have some specific need for it ? Would a CSV dumper be more suitable ?

**Comment by JavierMartinz** [comment]
I think is better this way, because the TCX is missing information like athlete name, cadence, etc

**Comment by dragosprotung** [comment]
The cadence is something that is missing from the library. I just need to add it as an extension. It's on my todo list. All the information is coming from polar, it's simply not extracted. But I think that fetching the workout as CSV is good to have

**Comment by JavierMartinz** [comment]
Thanks

**Pull request merged**
